include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "2.1.3"
    file: "common.yml"

variables:
  WEB_PORT: 8080
  REPLICA_COUNT: 1

stages:
  - linters
  - init
  - build
  - docker
  - deploy
  - undeploy

init:
  extends: .init-stage

  script:
    - source deploy-pipeline/build_env.sh
    - source deploy-pipeline/display_env.sh

linters: {extends: .linters-stage}
docker: {extends: .docker-stage}
deploy-prod: {extends: .deploy-prod-stage}
deploy-dev: {extends: .deploy-dev-stage}
undeploy: {extends: .undeploy-stage}
