include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "2.1.12"
    file: "react-app.yml"
  - local: "app.yml"

build:
  image: ${CI_REGISTRY}/${DOCKER_REGISTRY_PREFIX}/node:16.13.0-stretch
  script:
    - yarn install
    - yarn build
