variables:
  APP_NAME: secret-hitlerio
  NAMESPACE: llm-social-deduction
  CHILD_PIPELINE_EXECUTION_CONTEXT: secret-hitler
  WEB_PORT: 8080
  MAIN_URL: secrethitler-contest.net
  DEPLOYMENT_VARS: "MONGO_URL, MONGO_OPLOG_URL, MAIN_URL"
