version: "3.3"
services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: 5000
      MONGO_URL: "mongodb://database:27017/"
      REDIS_HOST: "redis"
    ports:
      - "5003:5000"
  database:
    image: mongo:7.0.5
    container_name: database
    restart: unless-stopped
    command: mongod
    ports:
      - "27017:27017"
  redis:
    image: redis:6.0.9
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
