version: "3.3"
services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: 8080
      MONGO_URL: "mongodb://database:27017/"
      REDIS_HOST: "localhost"
    ports:
      - "8080:8080"
  database:
    image: mongo:7.0.5
    container_name: database
    restart: unless-stopped
    command: mongod
    ports:
      - "27017:27017"
